server:
   port: 8045
##添加那个目录的文件需要restart
spring :
    devtools:
          restartadditional-paths: src/main/java
    ##排除那个目录的文件不需要restart
    ##spring.devtools.restart.exclude=static/**,public/**
    # 数据连接池
    datasource:
                url: jdbc:mysql://192.168.100.11:3306/guns?useUnicode=true&cracterEncoding=utf8&zeroDateTimeBevior=convertToNull
                username: root
                password: like
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.jdbc.Driver
                # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
                filters: stat,wall,log4j
                # 初始化大小，最小，最大
                initialSize: 5
                minIdle: 5
                maxActive: 20
                # 配置获取连接等待超时的时间
                maxWait: 60000
                # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
                timeBetweenEvictionRunsMillis: 60000
                # 配置一个连接在池中最小生存的时间，单位是毫秒
                minEvictableIdleTimeMillis: 300000
                validationQuery: select 'x'
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                # 打开PSCache，并且指定每个连接上PSCache的大小
                poolPreparedStatements: true
                maxOpenPreparedStatements: 20
                connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
                useGlobalDataSourceStat: true
# 整合mybatis
mybatis:
      mapperLocations: classpath:mybatis/mapper/*.xml
      typeAliasesPackage: com.xwcommon.xw_common_web.beans
# 整合logback 日志
logging:
  config: classpath:logback.xml
