# 项目根目录
server:
    context-path: /
spring:
  # 启用哪个配置文件
  profiles:
    active: prod
# 项目编码
http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#pagehelper分页插件配置
pagehelper:
         helperDialect: mysql
         reasonable: true
         supportMethodsArguments: true
         params: count=countSql
